apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  # Annotations create a certificate - no need for certificate.yaml
  annotations:
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/issuer: letsencrypt-staging
    # cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.global-static-ip-name: cluster-ip
  labels:
    # Timestamp used in order to force reload of the secret
    # last_updated: "1494099933"
    app: nginx
spec:
  backend:
    serviceName: nginx-php-service
    servicePort: 80
