apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: pvc-storage
          persistentVolumeClaim:
            claimName: pvc-claim
      containers:
      - name: nginx-php
        # Image built from this docker-compose.yml and pushed to Google repo
        image: gcr.io/modern-photon-112115/nginx-php:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - mountPath: "/mnt/data"
            name: pvc-storage
