apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc
spec:
  storageClassName: "standard-rwo"
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc-claim
  gcePersistentDisk:
    pdName: pvc
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
spec:
  storageClassName: "standard-rwo"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500G