apiVersion: v1
kind: Service
metadata:
  name: nginx-php-service
  annotations:
    # See https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip
    cloud.google.com/neg: '{"ingress": true}' # Creates a NEG after an Ingress is created
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - name: http-port
    port: 80
    targetPort: 8080
    protocol: TCP
    # I think this is needed for https
  - name: https-port
    port: 443
    targetPort: 8080
    protocol: TCP